### PR TITLE
package restructuring

### PR DESCRIPTION
**Pull request by ghost**
Removed the save_config in nsnitro.. 
And moved it inside a folder for doing from nsnitro import nsutil.

### CODE REVIEW

**Comment by favoretti** [comment]
Merged, let's see if that works out. So you're saying that `from nsnitro import *` doesn't work well?

**Comment by ghost** [comment]
it outright fails .... with some NSNitro not found error....  not sure about the call stack and part that triggers that error. ..somewhere inside nsresources is my first guess...

**Comment by favoretti** [comment]
Hmm, roll back the merge then? I won't be able to restructure it in the coming couple of days, would rock if github's head remained operational though.

**Comment by favoretti** [comment]
I reset the head to pre-merge state, let's test it first, don't wanna have it hanging around broken.

**Comment by ghost** [comment]
Oh... Ok... it's only from nsnitro import \* that fails... from nsnitro import nsnitro.. or from nsnitro.nsnitro import nsresources work fine..... 
Also i was able to run the example.py run and create,deleted, disabled,enabled the lbvservers accordingly....

**Comment by favoretti** [comment]
Oh, I misunderstood you then. Will put it back :)

**Comment by ghost** [comment]
Sorry for the extra work...  I should have updated this information on test cases along  with the pull request itself....

P.S: am using the restructured package for my tool and am developing around it..

**Comment by favoretti** [comment]
No prob, it's one command, re-merged already. Glad that you found this one useful :)

**Comment by ghost** [comment]
Oh.. just realized my previous msg was inaccurate. Am using this package at the moment only with the from nsnitro import nsnitro.py module.. i.e the get, put,  etc.. functions.. will need the lbvservers too later though...

**Comment by ghost** [comment]
Hey, by the way when are you planning to update the pypi egg package next ?? i might have to deploy my tool in 2 weeks time. Would be nice to be able to just easy_install :-P

**Comment by favoretti** [comment]
Oh, I didn't have pypi egg package at all yet. You think it's worth the effort? :)

**Comment by favoretti** [comment]
There ;) http://pypi.python.org/pypi/nsnitro/1.0.3

**Comment by ghost** [comment]
Oh... Great... I think being able to easy_install/pip install can be quite a boost in popularity of a python package in general... Ofcourse in this case i may be wrong.. we'll find out now won't we?? :-P

**Pull request merged**
