### PR TITLE
rename badly named get method

### PR DESCRIPTION
**Pull request by prune998**
replaced get_name() by get_monitorname() in get() methode

### CODE REVIEW

**Comment by favoretti** [comment]
Hey man, previous pull request flaked everything, would you be so kind to rebase and resubmit?

**Comment by prune998** [comment]
OK I will have a look. for the moment the latest pull I made does not solve the problem as I can’t add a new lbmonitor. debugging why. I’ll do another pull request once I’ve understood why.
Thanks.

**Comment by robison** [comment]
What version are you testing against? I only have 10.x images to test against right at the moment; this could be a version issue.

I'm working to get a private Jenkins job going that will run tests against a newly provisioned VPX image on every commit, if that'll help the testing process.

**Comment by favoretti** [comment]
Robison, when you have that job, can you check it in under contrib or so? Would be very helpful, as I can do the same, but also for 9.x

**Comment by prune998** [comment]
I’m using version : NS 10.1 122.17 and we’re going to upgrade to latest soon.

When using the nslbmonitor.py file from github, I am able to create a monitor entry.
Problem is when doing a get. The current code is as follow : 

```
@staticmethod
def get(nitro, monitor):
    """
    Use this API to fetch LB Monitor of given name.
    """
    __monitor = NSLBMonitor()
    __monitor.set_name(monitor.get_name())
    __monitor.get_resource(nitro)
    return __monitor
```

set_name() and get_name() is not defined in this class, but set_monitorname() and get_monitorname() are.

This is what my last pull request tried to solve. But this is not the only issue as, looking at the get_ressource code in nsbaseresource.py : 

```
def get_resource(self, nitro, object_name=None):
    url = "%s%s/%s" % (nitro.get_url(),
                       self.resourcetype,
                       object_name if object_name else self.options['name'])
    response = nitro.get(url)
```

There, get_ressource explicitly call to the object_name or  self.options['name’]  variable, which is not set in this case. So this call fail.

I haven’t been able to find a decent solution yet… any clue on your side ?

**Comment by robison** [comment]
Yeah, I'll submit a pull request for that shortly - there's some similar issues in other parts where 'name' just doesn't exist as an option and an alternative key is used to identify (NSAcl comes to mind; 'aclname' is used instead). We should just have to use:

```
@staticmethod
def get(nitro, monitor):
    """
    Use this API to fetch LB Monitor of given name.
    """
    __monitor = NSLBMonitor()
    __monitor.set_monitorname(monitor.get_monitorname())
    __monitor.get_resource(nitro, object_name=__monitor.get_monitorname())
    return __monitor
```

...instead. The nsbaseresource.py get_resource() looks like kind of a catch-all so that most other classes don't actually have to pass in the object_name (as you do in the 'delete' method in nslbmonitor.py, and others). Mea culpa; I forgot to include a test for getting the monitor names in my tests.py.

**Comment by prune998** [comment]
Hi

Coming back to you after some time… 
I’m still in the process of managing my LB using the nitro API. I can’t find a way to get the list of some bindings. For instance the nslbmonitorservicebinding.py does not include a ‘get’ function.

I’m still looking into it, hoping this is the only one, but I can’t confirm yet… this nitro API is so… large, at least… 

Do you think missing the get() is a miss or it is not the way to go ? 
My goal is first to be able to identify (create a dynamic schema) of each server with all dependencies… then being able to create them from start to end in one command depending on our needs… 

Thanks and kind regard for all your work.

Prune

**Comment by favoretti** [comment]
Java API also has no `get()` method, I just double-checked. That's why it's not there.
Basically for guidelines of what to port I just always look at Java classes.

**Comment by prune998** [comment]
This API is crap.
Seriously ? 

It seems, as far as I can see, they are using a get_nitro_response to get the raw response from the server… I’m actually looking at https://github.com/netscaler/nitro/blob/master/src/main/java/com/citrix/netscaler/nitro/resource/config/lb/lbmonitor_service_binding.java trying to understand how to manage all that and be able to list what is configured in the LB.
I thought using the API would be a time saving option… but actually, I’l losing solo much time on it… 
Prepare for me to come back to you regarding policies, as there are so many different kind ( queuing/Compression/AppSecure/Transform/Filter/Authorization/Rewrite/Responder/Cache/Syslog/Nslog/TMTraffic policy)… I may have to duplicate your policy function to handle each kind… except if you have a better idea ? 

Thanks again for all your work !
Prune

**Comment by robison** [comment]
I'd tend to agree, it looks like a direct port of the Java API. The good news is... I think this might give us a direction on doing really interesting things with 10.5, like getting functionality built in that allows us to control the filesystem operations and other neat features exposed in the 10.5 REST API.

Also, use of Requests... might be time to start talking about that in earnest.

**Comment by favoretti** [comment]
Filesystem operations are awesome, since we for one will be able to upload licenses via it :)
My question remains basically - should we keep supporting nsnitro or drop it in favor of whatever Citrix produced?

**Comment by prune998** [comment]
what will Citrix produce ?

**Comment by favoretti** [comment]
Ow, @robison - I think we accidentally mixed 2 threads :) @prune998 was referring to Java APi as crap (I hope), and we were discussing 10.5 Python API in the other issue.

@prune998 there's official citrix-supported Python API in 10.5 beta. Problem is - it's indeed the same "awesome" style - i.e. 1:1 Java port, which is not really pythonic by any means. (Not that my implementation is 100% pythonic, but at least it tries to come there. What's I'd for instance do with nsnitro is also decorate every getter and setter with `@property`, etc.. 

My problem is - if everyone migrates to Citrix official API - would it make sense to keep this one alive? Even if we migrate to requests with sessions and so on.

**Comment by prune998** [comment]
did you had a change to get hands on the 10.5 beta ? 
how will they release it ? 

It seems citrix changes A LOT of things at every version... overriding their own python API would certainely be easier.
While Citrix (crapy) JAVA API is a 1:1 to what you do in the interface, it is little help to get the same thing in python. 
Why not use the Citrix Python API and work over it to offer a "pythonic" usable interface to core functions ? 
By that, I mean, for example, having a function to create a SSL virtual server, instead of having to create a service group, SFTP upload a SSL cert, create a SSL entity, bind the vserver to the ssl cert, add SNI to the ssl binding...

**Comment by favoretti** [comment]
Closing as this was already tackled and this isn't merge'able.

**Pull request closed without merging**
