### PR TITLE
Refactored to use Requests instead of URLLib2

### PR DESCRIPTION
**Pull request by robison**

### CODE REVIEW

**Comment by ndenev** [comment]
Isn't it better to also use a session object if we switch to Requests so we can have http-keepalive, etc?
Without it there is not much benefit I guess...

**Comment by robison** [comment]
Agreed, I think I jumped the gun a bit on this. Working on it.

**Comment by favoretti** [comment]
Seeing this a bit late, but even if we move to requests, whether for benefits or for fun, as requests is not a part of standard python library, I'd actually make the first implementation in such a way that people for instance can choose which lib to use by passing a parameter to NSNitro constructor, keeping default on urllib2 initially, to allow for backwards-compatibility. Just switching to requests will break the library on the systems where requests is not installed, and not all systems are able to pull packages from pip as dependencies.

Or am I being too careful here?

**Comment by robison** [comment]
Nope, I believe that you're absolutely right. Plus, my code was crap and not properly tested, so there's that. I do have reasons for wanting to use Requests, but I'd also like to see about supporting the 10.x+ API, since I don't believe that the legacy 9.2 API will be supported for too much longer. I'm going to work on that in my own fork, but I'm not sure what the best way to help contribute those changes back into the main repo might be.

**Comment by favoretti** [comment]
Basically I'd be very happy if you could point me out to 10.x specific code, then I suppose I could for now incorporate 10.x support in the current lib. I believe the only thing that changes is that you need to send some new content-type and header format changed a bit? Main object structure remained the same, right?

On the topic of requests - I'd love to know the reasons (if they aren't classified), and we could always release nsnitro 2.0 which is requests-based, keep supporting 1.x branch for a bit and drop it in the long run. Not like requests is going to disappear anywhere soon and even if so, we could always fork it inside nsnitro.

**Comment by robison** [comment]
Right, it's basically stayed the same from an object standpoint, with the following few changes:
1. Full URI is required to create or update an object, instead of simply hitting the base URL 
2. Content-type cookie must be set correctly, matching the type of object being created/updated/deleted - form is of 'application/vnd.com.citrix.netscaler.<nsfeature>+json'
3. Login cookie is now named NITRO_AUTH_TOKEN
4. HTTP responses seem more HATEOAS compliant, only returning HTTP 200/201 upon a successful PUT/POST request and no JSON response body (i.e.: no more 'errorcode: 0' responses after a 200/201). This should allow us to simply look for a JSON-formatted response based on a 4xx-5xx HTTP return code for PUTs/POSTs.

All fairly straightforward stuff, I think. I've been tinkering with a fork to learn the API; I'm going to work this week on converting some of the (admittedly extensive) changes that I've done into actual useful pull requests for the main repo.

As far as the Requests library, I'd like to see about using that instead of having to go about passing the auth token around, and instead letting requests.session() handle that from a cookie perspective. We'd have to instantiate requests.session() at login time and then pass that around as the method by which the functions in nsnitro.py access the API. Or am I completely off base there? Just some ideas - I'm definitely a neophyte when it comes to this realm.

**Pull request closed without merging**
